### ISSUE TITLE
add grid on comut plot

### ISSUE THREAD

**Issue by mjko1210** [vanallenlab/comut#10]
Hi,

Is it possible to add grid to plots generated by `add_continuous_data` and `add_continuous_data`.

For example, I want to add grey grid lines like this plot.
![Screen Shot 2020-08-12 at 12 26 56 PM](https://user-images.githubusercontent.com/9116362/90058932-3eccc100-dc97-11ea-9cb6-a3c3eff3c812.png)

Thanks for your advice!

**Comment by jett-crowdis** [comment]
Yes, this is possible by editing the individual axes. There is a function in matplotlib called `ax.grid` that will add gridlines to an axis object. By default this grid doesn't line up with the comut's patches, so you'll need to do some tinkering. Let's say I wanted to add such a grid to a categorical dataset named `'Mutation type'`

```python
from matplotlib.ticker import AutoMinorLocator # this function sets the location of the minor tick mark
minor_locator = AutoMinorLocator(2) # will place minor ticks in between major ticks

# set the axis minor tick locations to these positions
comut.axes['Mutation type'].yaxis.set_minor_locator(minor_locator)
comut.axes['Mutation type'].xaxis.set_minor_locator(minor_locator)

# add the grid
comut.axes['Mutation type'].grid(which='minor', color='black')

# the spines by default are off, so we need to add them back
comut.axes['Mutation type'].spines['left'].set_visible(True)
comut.axes['Mutation type'].spines['bottom'].set_visible(True)
```
The process is exactly the same for continuous data
