### ISSUE TITLE
plot 2 category variables in the same panel

### ISSUE THREAD

**Issue by sahuno** [vanallenlab/comut#11]
Hi @jett-crowdis 

thanks for making such a useful tool. any thoughts on how i can plot 2 categorical variables in the same panel? 
for instance show difference between copy number of a gene (say TP53) for same patient detected with
different methods 1. from cell-free DNA and 2. solid tumor biopsies 
to be in the same box as shown in this plot [](https://www.nature.com/articles/s41467-017-00965-y/figures/3)
<img width="1278" alt="copy_number_Comut_tumorNcfDNA" src="https://user-images.githubusercontent.com/38211023/91172969-0f608000-e6ab-11ea-9b7a-91c94f932f87.png">

thanks for your help

**Comment by jett-crowdis** [comment]
You can absolutely do this! The way to do it is to classify mutations as either "tumor" or "cfDNA" as a prefix to the mutation. For each sample, they might have a "cfDNA-Missense" or a "tumor-Missense" mutation. You can then simply map the mutations to the same color value, e.g. `mapping = {'cfDNA-Missense': 'black', 'tumor-Missense': 'black'}`. This will show the two mutations as triangles.

When you make the legend, it will create separate categories for cfDNA and tumor mutations. You can fix this by grabbing the legend elements with `ax.get_legend_handles_labels` and then subsetting to just the ones you want (changing their labels). Check the [matplotlib legend guide](https://matplotlib.org/tutorials/intermediate/legend_guide.html) for more info.

To ensure that the cf-DNA mutations are always on the "top" of the two triangles, you can use the `value_order` argument of `add_categorical_data`. Just pass a list of mutations with all the `cf-DNA` prefixed mutations before all the `tumor` prefixed mutations. 

Unfortunately, there's no way with the current comut structure to change the size of triangles as shown in the figure you provided. If you wanted a way to hack this in, you could simply leave nonclonal mutations blank (so they will show up as grey triangles), and then draw over the plot yourself.

**Comment by sahuno** [comment]
thanks @jett-crowdis 
Great strategy!

Sam

**Comment by sahuno** [comment]
Hi @jett-crowdis thanks for the previous suggestions. I did the double copy number plot with triangles but was unable to specify the right-angle triangles as legends with `ax.get_legend_handles_labels ` This what i tried. any suggestions to get the correct right-angle triangles (as in the main figure below) for the legend would be much appreciated.  Thanks in advance.

```
##define right angles triangles
angle=180
verts_ob = [[-1, -1], [1, -1], [1, 1], [-1, -1]]
verts = mpl.markers.MarkerStyle(marker=verts_ob)
verts._transform = verts.get_transform().rotate_deg(angle)

HAMP_triangle_cna = mlines.Line2D([], [], color='#001261', marker=verts_ob, linestyle='None',mec='white', mfc='#001261', mew=1, markersize=100)
AMP_triangle_cna = mlines.Line2D([], [], color='#001261', marker=r'$\blacktriangleleft/\blacktriangleright$', linestyle='None',mec='white', mfc='#31598A', mew=1, markersize=200)
```


![Screen Shot 2021-01-15 at 5 49 05 AM](https://user-images.githubusercontent.com/38211023/104716198-93b4ad80-56f5-11eb-8dbd-c79e5ef5097c.png)

**Comment by jett-crowdis** [comment]
Glad to hear you got it to work!

Unfortunately, this a known issue with matplotlib legend handles - the shapes that they can show by default are extremely limited. I think you have two options:

1. Try to create your own custom legend patch using an artist like in https://matplotlib.org/tutorials/intermediate/legend_guide.html. There are patches you can make using polygons to make your right triangles, but I'm not entirely sure the legend will handle them correctly.

2. Just create your own patch and plot it on the figure itself. So you would create a patch (like above), but then add it directly to the figure around the legend. You could then use empty handles in the legend. The issue with this, of course, is that you'll have to manually place the patches where the legend is. You can either does this manually or try to identify the location of the legend handles (I'm sure there's an attribute that details this).

Hope that helps!

**Comment by virdzek-g** [comment]
I just thought I will show here my solution to this issue in case anyone new is also struggling with this.

1.) Combine data frames of the two categorical variables into a single data frame (**columns** = _sample_, _category_, _value_ (with prefix e.g. tumor-missense, cfDNA-missense, site (e.g. tumor / cfDNA))
2.) If there are multiple mutations in the same sample+category+site, replace these rows with a single row with value=cfDNA-multiple / tumor-multiple
3.) identify sample+category+site which are unique in each of the original data frame (i.e. combination of patient+gene which are present only in either original data frame (e.g. cfDNA or tumor) . For each of these unique sample+category+site values create a new row, where sample+category+site are the same and value=empty
4.) assign all value = cfDNA-*** to value_order to be in the upper left corner
5.) value=empty color as white

```
value_order = ['cfDNA-In frame indel','cfDNA-multiple', 'cfDNA-Splice Site','cfDNA-Frameshift indel','cfDNA-Missense mutation']

mapping = {'cfDNA-In frame indel': '#5F5F5F', 'tumor-In frame indel': 'black',
         'cfDNA-Missense mutation': '#2B94F1','tumor-Missense mutation':'#196EBA',
          'cfDNA-Frameshift indel':'#65C520','tumor-Frameshift indel':'#1E8449',
          'cfDNA-Splice Site':'#E0455C','tumor-Splice Site':'#A3172C',
          'empty':'white','empty-c':'white', 'cfDNA-multiple':'#B7950B'}
```

The resulting figure will look like this:
<img width="513" alt="Screen Shot 2022-08-29 at 09 21 18" src="https://user-images.githubusercontent.com/82646598/187212648-536ada2b-dcd0-4d8d-b6f1-f3436e0a2f03.png">

It's a bit tricky but seems like the easiest solution to this issue to me.
