### ISSUE TITLE
ytick.labelsize

### ISSUE THREAD

**Issue by mjko1210** [vanallenlab/comut#9]
Hi,

Is it possible to set `ytick.labelsize` separately for each plot?
For example, I have barplots and few other plots (from add_categorical_data). I wish I can set `ytick.labelsize` separately for each plot.

Thanks!
MJ

**Comment by jett-crowdis** [comment]
Hi there!

This is not possible using `add_categorical_data` but is possible by changing the axes objects after the comut has been created. `ax.tick_params(axis = 'y', which = 'major', labelsize = fontsize)` should be what you're looking for.

So if you want to increase the ytick labelsize for your barplot named `'Mutation_Burden'` to 16, you would do:
`comut.axes['Mutation_Burden'].tick_params(axis = 'y', which = 'major', labelsize = fontsize)`, and then you can see it changed in the figure with `comut.figure`.

In general, if you'd like to change something specific to an axis, changing the axis object is the way to go!
